import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getRequestContext } from '@/lib/auth/context';
import { createClient } from '@/lib/supabase/server';
import { audit } from '@/lib/server/audit';
const schema=z.object({feature_name:z.string().regex(/^[a-z0-9_\-]{2,80}$/),enabled:z.boolean()});
async function adminContext(){const ctx=await getRequestContext();if(ctx.role!=='super_admin')throw new Response('Forbidden',{status:403});return ctx}
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){try{await adminContext();const {id}=await params;const supabase=await createClient();const {data,error}=await supabase.from('feature_flags').select('feature_name,enabled').eq('tenant_id',id).order('feature_name');if(error)throw error;return NextResponse.json({data})}catch(e){if(e instanceof Response)return e;return NextResponse.json({error:'tenant_features_fetch_failed'},{status:500})}}
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){try{const ctx=await adminContext();const {id}=await params;const body=schema.parse(await req.json());const supabase=await createClient();const {data:tenant,error:tenantError}=await supabase.from('tenants').select('id').eq('id',id).maybeSingle();if(tenantError)throw tenantError;if(!tenant)return NextResponse.json({error:'not_found'},{status:404});const {data,error}=await supabase.from('feature_flags').upsert({tenant_id:id,feature_name:body.feature_name,enabled:body.enabled,updated_at:new Date().toISOString()},{onConflict:'tenant_id,feature_name'}).select().single();if(error)throw error;await audit({tenantId:ctx.tenantId,userId:ctx.userId,action:'platform.feature.update',entity:'feature_flag',entityId:body.feature_name,metadata:{target_tenant:id,enabled:body.enabled}});return NextResponse.json({data})}catch(e){if(e instanceof Response)return e;if(e instanceof z.ZodError)return NextResponse.json({error:'invalid_payload'},{status:400});return NextResponse.json({error:'tenant_feature_update_failed'},{status:500})}}
