'use client';
import { useEffect,useMemo,useState } from 'react';
import { Users, UserPlus, MessagesSquare, TrendingUp, WalletCards } from 'lucide-react';
type Data={activeContacts:number;leads:number;openConversations:number;conversion:number;openPipeline:number;leadSeries:{day:string;count:number}[]};
const empty:Data={activeContacts:0,leads:0,openConversations:0,conversion:0,openPipeline:0,leadSeries:[]};
export default function Dashboard(){
 const [data,setData]=useState<Data>(empty);const [loading,setLoading]=useState(true);
 useEffect(()=>{fetch('/api/dashboard',{cache:'no-store'}).then(r=>r.json()).then(d=>setData(d.data??empty)).finally(()=>setLoading(false))},[]);
 const max=useMemo(()=>Math.max(1,...data.leadSeries.map(x=>x.count)),[data.leadSeries]);
 const stats=[['Contatos ativos',String(data.activeContacts),Users],['Leads em aberto',String(data.leads),UserPlus],['Atendimentos abertos',String(data.openConversations),MessagesSquare],['Conversão',`${data.conversion.toLocaleString('pt-BR')}%`,TrendingUp],['Pipeline',data.openPipeline.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),WalletCards]] as const;
 return <div className="content"><h1 className="page-title">Visão geral</h1><p className="page-sub">Indicadores calculados a partir dos dados reais do seu tenant.</p>{loading?<div className="card empty">Carregando indicadores...</div>:<><div className="grid stats stats-five">{stats.map(([label,value,Icon])=><div className="card stat" key={label}><div className="stat-head"><div className="stat-icon"><Icon size={18}/></div></div><div className="stat-value">{value}</div><div className="stat-label">{label}</div></div>)}</div><div className="grid dashboard-two"><section className="card section"><h3>Leads nos últimos 7 dias</h3><div className="bars">{data.leadSeries.map(x=><div key={x.day} className="bar-wrap" title={`${x.day}: ${x.count}`}><div className="bar" style={{height:`${Math.max(8,(x.count/max)*100)}%`}}/><small>{new Date(`${x.day}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'short'}).replace('.','')}</small></div>)}</div></section><section className="card section"><h3>Resumo comercial</h3><div className="activity"><div className="dot"/><div><strong>{data.openConversations} conversas em atendimento</strong><div className="muted">Caixa de entrada ativa</div></div></div><div className="activity"><div className="dot"/><div><strong>{data.leads} leads aguardando avanço</strong><div className="muted">Base de oportunidades</div></div></div><div className="activity"><div className="dot"/><div><strong>{data.openPipeline.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong><div className="muted">Valor do pipeline aberto</div></div></div></section></div></>}</div>
}