'use client';
import { FormEvent, useEffect, useState } from 'react';
import { Send, MoreHorizontal, Plus, X } from 'lucide-react';

type Message={id:string;direction:string;body:string;created_at:string};
type Conversation={id:string;status:string;channel:string;contact:{id:string;name:string;email?:string;phone?:string};messages:Message[]};
type Contact={id:string;name:string;email?:string;phone?:string};
export default function Atendimento(){
 const [items,setItems]=useState<Conversation[]>([]);const [contacts,setContacts]=useState<Contact[]>([]);const [active,setActive]=useState<Conversation|null>(null);const [text,setText]=useState('');const [loading,setLoading]=useState(true);const [creating,setCreating]=useState(false);const [error,setError]=useState('');
 async function load(){setLoading(true);const [cr,ct]=await Promise.all([fetch('/api/conversations',{cache:'no-store'}),fetch('/api/contacts',{cache:'no-store'})]);const [cd,td]=await Promise.all([cr.json(),ct.json()]);if(cr.ok){setItems(cd.data??[]);setActive(v=>{if(!v)return cd.data?.[0]??null;return (cd.data??[]).find((x:Conversation)=>x.id===v.id)??cd.data?.[0]??null})}if(ct.ok)setContacts(td.data??[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function send(e:FormEvent){e.preventDefault();if(!text.trim()||!active)return;setError('');const r=await fetch(`/api/conversations/${active.id}/messages`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({body:text})});const d=await r.json();if(r.ok){setText('');await load()}else setError(d.error==='external_channel_requires_configured_provider'?'Este canal externo ainda não possui provedor configurado.':'Não foi possível enviar a mensagem.')}
 async function createConversation(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const r=await fetch('/api/conversations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contact_id:fd.get('contact_id'),channel:'internal'})});const d=await r.json();if(r.ok){setCreating(false);await load();setActive({...(d.data as Conversation),contact:contacts.find(c=>c.id===d.data.contact_id)??contacts[0],messages:[]} as Conversation)}else setError('Você não possui permissão para iniciar este atendimento.')}
 return <div className="chat-layout"><aside className="chat-list"><div className="chat-list-head"><div><strong>Atendimentos</strong><div className="muted" style={{fontSize:12}}>Caixa de entrada unificada</div></div><button className="btn btn-primary icon-btn" onClick={()=>setCreating(v=>!v)} aria-label="Novo atendimento">{creating?<X size={16}/>:<Plus size={16}/>}</button></div>{creating&&<form className="chat-new" onSubmit={createConversation}><select className="select" name="contact_id" required defaultValue=""><option value="" disabled>Selecione um contato</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="btn btn-primary">Iniciar</button></form>}{loading?<div className="empty">Carregando...</div>:items.length===0?<div className="empty">Nenhum atendimento ainda.</div>:items.map(c=><button type="button" className={`conversation conversation-button ${active?.id===c.id?'active':''}`} key={c.id} onClick={()=>setActive(c)}><div className="conversation-top"><strong>{c.contact?.name??'Contato'}</strong><small className="muted">{c.status}</small></div><p>{c.messages?.at(-1)?.body??'Sem mensagens'}</p></button>)}</aside><section className="chat-center">{active?<><div className="chat-header"><div><strong>{active.contact?.name??'Contato'}</strong><div className="muted" style={{fontSize:12}}>{active.contact?.phone??active.contact?.email??'Contato CRM'} · {active.channel}</div></div><button className="btn btn-secondary"><MoreHorizontal size={18}/></button></div><div className="chat-messages">{active.messages?.length?active.messages.map(m=><div key={m.id} className={`msg ${m.direction==='outbound'?'out':'in'}`}>{m.body}</div>):<div className="empty">Envie a primeira mensagem deste atendimento.</div>}</div><form className="composer" onSubmit={send}><input className="input" value={text} onChange={e=>setText(e.target.value)} placeholder="Digite uma mensagem..."/><button className="btn btn-primary"><Send size={17}/>Enviar</button></form>{error&&<div className="chat-error">{error}</div>}</>:<div className="empty">Selecione uma conversa.</div>}</section><aside className="chat-details">{active&&<><h3>{active.contact?.name}</h3><p className="muted">{active.contact?.email}</p><p className="muted">{active.contact?.phone}</p><hr/><strong>Segurança</strong><p className="muted" style={{fontSize:13}}>Toda leitura e escrita usa o tenant do usuário autenticado. IDs externos não ampliam o escopo da consulta.</p></>}</aside></div>
}