'use client';
import { FormEvent, useEffect, useState } from 'react';
import { Send, MoreHorizontal } from 'lucide-react';

type Conversation={id:string,status:string,contact:{id:string,name:string,email?:string,phone?:string},messages:{id:string,direction:string,body:string,created_at:string}[]};
export default function Atendimento(){const [items,setItems]=useState<Conversation[]>([]);const [active,setActive]=useState<Conversation|null>(null);const [text,setText]=useState('');const [loading,setLoading]=useState(true);
 async function load(){setLoading(true);const r=await fetch('/api/conversations',{cache:'no-store'});const d=await r.json();setItems(d.data??[]);setActive(v=>v??d.data?.[0]??null);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function send(e:FormEvent){e.preventDefault();if(!text.trim()||!active)return;const r=await fetch(`/api/conversations/${active.id}/messages`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({body:text})});if(r.ok){setText('');await load();}}
 return <div className="chat-layout"><aside className="chat-list"><div style={{padding:18}}><strong>Atendimentos</strong><div className="muted" style={{fontSize:12}}>Caixa de entrada unificada</div></div>{loading?<div className="empty">Carregando...</div>:items.length===0?<div className="empty">Nenhum atendimento ainda.</div>:items.map(c=><div className={`conversation ${active?.id===c.id?'active':''}`} key={c.id} onClick={()=>setActive(c)}><div className="conversation-top"><strong>{c.contact?.name??'Contato'}</strong><small className="muted">{c.status}</small></div><p>{c.messages?.at(-1)?.body??'Sem mensagens'}</p></div>)}</aside><section className="chat-center">{active?<><div className="chat-header"><div><strong>{active.contact.name}</strong><div className="muted" style={{fontSize:12}}>{active.contact.phone??active.contact.email??'Contato CRM'}</div></div><button className="btn btn-secondary"><MoreHorizontal size={18}/></button></div><div className="chat-messages">{active.messages?.map(m=><div key={m.id} className={`msg ${m.direction==='outbound'?'out':'in'}`}>{m.body}</div>)}</div><form className="composer" onSubmit={send}><input className="input" value={text} onChange={e=>setText(e.target.value)} placeholder="Digite uma mensagem interna ao atendimento..."/><button className="btn btn-primary"><Send size={17}/>Enviar</button></form></>:<div className="empty">Selecione uma conversa.</div>}</section><aside className="chat-details">{active&&<><h3>{active.contact.name}</h3><p className="muted">{active.contact.email}</p><p className="muted">{active.contact.phone}</p><hr style={{border:0,borderTop:'1px solid var(--line)',margin:'18px 0'}}/><strong>Contexto</strong><p className="muted" style={{fontSize:13}}>Dados sempre filtrados pelo tenant autenticado. O backend não aceita tenant_id enviado pelo navegador.</p></>}</aside></div>}
