import { NextResponse } from 'next/server';
import { z } from 'zod';
import { requirePermission } from '@/lib/auth/context';
import { createClient } from '@/lib/supabase/server';
import { requireFeature } from '@/lib/server/feature';
import { audit } from '@/lib/server/audit';
const patch=z.object({name:z.string().trim().min(2).max(160).optional(),enabled:z.boolean().optional(),config:z.record(z.unknown()).optional()});
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){try{const ctx=await requirePermission('automations.manage');await requireFeature(ctx,'automacoes');const {id}=await params;const body=patch.parse(await req.json());const supabase=await createClient();const {data,error}=await supabase.from('automations').update({...body,updated_at:new Date().toISOString()}).eq('id',id).eq('tenant_id',ctx.tenantId).select().maybeSingle();if(error)throw error;if(!data)return NextResponse.json({error:'not_found'},{status:404});await audit({tenantId:ctx.tenantId,userId:ctx.userId,action:'automation.update',entity:'automation',entityId:id,metadata:body});return NextResponse.json({data})}catch(e){if(e instanceof Response)return e;if(e instanceof z.ZodError)return NextResponse.json({error:'invalid_payload'},{status:400});return NextResponse.json({error:'automation_update_failed'},{status:500})}}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){try{const ctx=await requirePermission('automations.manage');await requireFeature(ctx,'automacoes');const {id}=await params;const supabase=await createClient();const {data,error}=await supabase.from('automations').delete().eq('id',id).eq('tenant_id',ctx.tenantId).select('id').maybeSingle();if(error)throw error;if(!data)return NextResponse.json({error:'not_found'},{status:404});await audit({tenantId:ctx.tenantId,userId:ctx.userId,action:'automation.delete',entity:'automation',entityId:id});return NextResponse.json({ok:true})}catch(e){if(e instanceof Response)return e;return NextResponse.json({error:'automation_delete_failed'},{status:500})}}
